{'archived': False,
 'created_by': {'id': 'e1f286c2-13b8-47f0-ac9d-7fc3ea28f030',
                'object': 'user'},
 'created_time': '2022-02-23T13:40:00.000Z',
 'has_children': False,
 'heading_2': {'text': [{'annotations': {'bold': False,
                                         'code': False,
                                         'color': 'default',
                                         'italic': False,
                                         'strikethrough': False,
                                         'underline': True},
                         'href': None,
                         'plain_text': 'Привет',
                         'text': {'content': 'Привет',
                                  'link': None},
                         'type': 'text'},
                        {'annotations': {'bold': False,
                                         'code': False,
                                         'color': 'default',
                                         'italic': False,
                                         'strikethrough': False,
                                         'underline': False},
                         'href': None,
                         'plain_text': ', ',
                         'text': {'content': ', ',
                                  'link': None},
                         'type': 'text'},
                        {'annotations': {'bold': True,
                                         'code': False,
                                         'color': 'default',
                                         'italic': False,
                                         'strikethrough': False,
                                         'underline': False},
                         'href': 'https://ya.ru',
                         'plain_text': 'м',
                         'text': {'content': 'м',
                                  'link': {'url': 'https://ya.ru'}},
                         'type': 'text'},
                        {'annotations': {'bold': True,
                                         'code': False,
                                         'color': 'default',
                                         'italic': False,
                                         'strikethrough': False,
                                         'underline': False},
                         'href': None,
                         'plain_text': 'ир',
                         'text': {'content': 'ир',
                                  'link': None},
                         'type': 'text'},
                        {'annotations': {'bold': False,
                                         'code': False,
                                         'color': 'default',
                                         'italic': False,
                                         'strikethrough': False,
                                         'underline': False},
                         'href': None,
                         'plain_text': '!',
                         'text': {'content': '!',
                                  'link': None},
                         'type': 'text'}]},
 'id': 'e31ac8ad-eeaf-4c07-a335-3057fe9e62ed',
 'last_edited_by': {'id': 'e1f286c2-13b8-47f0-ac9d-7fc3ea28f030',
                    'object': 'user'},
 'last_edited_time': '2022-02-23T13:43:00.000Z',
 'object': 'block',
 'type': 'heading_2'}
